model_selection:
  model:
    Random Forest:
      search_param_grid:
        n_estimators: 
          - 100
          - 200
          - 300
        max_depth: 
          - null
          - 5
          - 10
        min_samples_split: 
          - 2
          - 5
          - 10
        min_samples_leaf: 
          - 1
          - 2
          - 4

    XG Boost:
      search_param_grid:
        learning_rate: 
          - 0.1
          - 0.01
          - 0.001
        max_depth: 
          - 3
          - 5
          - 7
        n_estimators: 
          - 100
          - 200
          - 300
        gamma: 
          - 0
          - 0.1
          - 0.2

    Extra Trees:
      search_param_grid:
        criterion: 
          - gini
          - entropy
        max_depth: 
          - null
          - 5
          - 10
        min_samples_split: 
          - 2
          - 5
          - 10
        min_samples_leaf: 
          - 1
          - 2
          - 4

    KNN:
      search_param_grid:
        n_neighbors: 
          - 3
          - 5
          - 7
        weights: 
          - uniform
          - distance
        algorithm: 
          - ball_tree
          - kd_tree
        leaf_size:
          - 30
          - 60
          - 90
        p:
          - 1
          - 2

    Decision Tree:
      search_param_grid:
        criterion: 
          - gini
          - entropy
        splitter: 
          - best
          - random
        max_depth: 
          - null
          - 5
          - 10
        min_samples_split: 
          - 2
          - 5
          - 10
        min_samples_leaf: 
          - 1
          - 2
          - 4

    Gradient Boosting:
      search_param_grid:
        n_estimators:
          - 100
        criterion:
          - friedman_mse
        max_depth:
          - 3
          - 5
          - 7

    AdaBoost Classifier:
      search_param_grid:
        n_estimators:
          - 50
          - 100
          - 200
